ansible_port: 5422
ansible_ssh_private_key_file: /home/arthur/.ssh/maddog

host_user: deploy
work_dir: /srv/www/maddog
django_debug: False
django_settings_module: core.settings.prod

allowed_hosts: ".maddogclub.com"
