- name: docker| volume | exists
  command: docker volume inspect pgdata
  register: volume_exists
  failed_when: false

- name: docker| volume | create
  command: docker volume create --name pgdata
  when: volume_exists|failed

- name: docker | container | postgres
  docker_container:
    name: postgres
    image: pyeye/md-postgres:9.5-2
    pull: true
    state: started
    restart_policy: always
    volumes:
      - "pgdata:/var/lib/postgresql/data"
      - "{{work_dir}}/src/data/dump:/srv/www/maddog/src/data/dump"
    ports:
      - "5432:5432"
    env:
      POSTGRES_USER: "{{db_user}}"
      POSTGRES_DB: "{{db_name}}"
      POSTGRES_PASSWORD: "{{db_password}}"
  tags:
    - containers
