- name: docker | container | django
  docker:
    name: django
    image: pyeye/md-django:latest
    pull: always
    state: reloaded
    restart_policy: always
    command: "gunicorn core.wsgi:application -w 3 -b 0.0.0.0:8000 --reload --env DEBUG={{debug}}"
    links:
    - "postgres:postgres"
    volumes:
    - "{{work_dir}}/src/backend/:/srv/www/maddog/src/backend/"
    - "{{work_dir}}/src/media/:/srv/www/maddog/src/media/"
    - "{{work_dir}}/src/static/:/srv/www/maddog/src/static/"
  tags:
    - containers
